<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="D-N-PC-13103" failures="0" tests="9" name="validator.CoordinateTest" time="2.109" errors="1" timestamp="2023-03-18T15:30:53 IRST" skipped="0">
  <testcase classname="validator.CoordinateTest" name="testValidCoordinate" time="0.236"/>
  <system-out/>
  <testcase classname="validator.CoordinateTest" name="testValidCoordinate" time="0.250"/>
  <system-out/>
  <testcase classname="validator.CoordinateTest" name="testValidCoordinate" time="0.250"/>
  <system-out/>
  <testcase classname="validator.CoordinateTest" name="testValidCoordinate" time="0.215"/>
  <system-out/>
  <testcase classname="validator.CoordinateTest" name="testValidCoordinate" time="0.232"/>
  <system-out/>
  <testcase classname="validator.CoordinateTest" name="testValidCoordinate" time="0.199"/>
  <system-out/>
  <testcase classname="validator.CoordinateTest" name="testValidCoordinate" time="0.264"/>
  <system-out/>
  <testcase classname="validator.CoordinateTest" name="testInvalidCoordinate" time="0.205">
    <error message="
Method CoordinateTest.testInvalidCoordinate()[pri:0, instance:validator.CoordinateTest@694abbdc] should have thrown an exception of type class javax.validation.ConstraintViolationException" type="org.testng.TestException">
      <![CDATA[org.testng.TestException: 
Method CoordinateTest.testInvalidCoordinate()[pri:0, instance:validator.CoordinateTest@694abbdc] should have thrown an exception of type class javax.validation.ConstraintViolationException
at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:82)
at org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:749)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:634)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
    </error>
  </testcase> <!-- testInvalidCoordinate -->
  <system-out/>
  <testcase classname="validator.CoordinateTest" name="testValidCoordinate" time="0.258"/>
  <system-out/>
</testsuite> <!-- validator.CoordinateTest -->
